services:
  bookcrossing:
    build:
      context: ./bookcrossing
    ports:

      - "8000:5000"
    environment:
      - DATABASE_URL=${DB_URL}
    depends_on:
      - db
    networks:
      - fastapi-network
  get_url:
    build:
      context: ./get_url
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - get_url

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:

      - postgres-data:/var/lib/postgresql/data
    networks:
      - fastapi-network

volumes:
  postgres-data:


networks:
  fastapi-network:
